### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by arlissc** [mozillascience/global-sprint-2016#4]
**ROADMAP:**

**T-12 Weeks: (week of Feb 29 2016)**

- [x] Build Global Sprint PLAN
- [x] Kick-off Meeting - Proposed:  Wednesday March 09, 10:30 AM ET
- [x] SAVE THE DATE - blog post / email blast / Twitter post (maybe once blog post is written)
- [x] Finalize Project Team roles & responsibilities
- [x] Design Project submission form (new for 2016)
- [x] Design Site Host submission form (new for 2016)
- [x] Discuss swag opportunities

**T-10 Weeks: (week of March 14 2016)**

- [x] Initial announcement
- [x] Include call for site hosts
- [ ] Finalize site map format / location (new for 2016)
- [ ] Discuss promotional materials for Site Hosts
- [ ] Discuss swag offerings

**T-8 Weeks: (week of March 21 2016)**

- [ ] Progress meeting
- [ ] Order swag offerings
- [ ] Twitter stream - design daily tweets to start T-6 weeks
- [ ] Design registration procedures
- [ ] script to turn locations into geojson for mapping or another format
- [ ] Targeted solicitation for projects email
- [ ] Targeted solicitation for sites email
- [ ] Design pre / post assessment surveys - co-ordinate with CMU
- [ ] Finalize swag packs

**T-6 Weeks: (week of April 04 2016)**

- [ ] Progress meeting
- [ ] Progress report
- [ ] Blog Post: sites & projects so far
- [ ] Twitter stream
- [ ] Begin soliciting project guest blogs

**T-4 Weeks: (week of April 18 2016)**

- [ ] Site submissions closes
- [ ] Progress meeting
- [ ] Progress report
- [ ] Blog Post: sites & projects so far
- [ ] Final call for projects & sites
- [ ] Twitter stream (1/day)

**T-16 Days: (April 29 2016)**

- [ ] last call for project submissions
- [ ] Twitter Stream
- [ ] Webconferencing testing with Site Hosts starts
- [ ] Finalize “Day Of” format
- [ ] check-in / demos schedules

**T-2 Weeks: (week of May 02 2016)**

- [ ] Twitter stream
- [ ] Blog: FAQ

**T-6 Days: (May 27 2016)**

- [ ] Spool up final communications with projects & sites
- [ ] Email blasts

**T+0 Days: (June 02 2016)**

- [ ] Begin live broadcast
- [ ]    * vidyo
- [ ]    * possible to turn twitter & github analytics into R-shiny web app? Probably.
- [ ]    * begin live-tweeting event

**T+2 Days: (June 04 2016)**

- [ ] Wrap up
- [ ] blog
- [ ] email
- [ ] tweets
- [ ] Project lead thank you email
- [ ] Site host thank you email
- [ ] Follow-up on post-event surveys
- [ ] Maybe launch applications for our next WOW / OLC?

T**+5 Days: (June 08 2016)**

- [ ] Report back
- [ ] Storify #mozsprint
- [ ] blog analytics + map
- [ ]      * https://www.mozillascience.org/you-did-this-mozilla-science-global-sprint-2015/
- [ ] Debrief with team, debrief with site hosts -- ask them if anyone stood out from their sites

**Comment by acabunoc** [comment]
Moved to https://github.com/mozillascience/plan/issues/70
